TOP=../
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

INC += ur_rtde/rtde_receive_interface_doc.h
INC += ur_rtde/rtde_receive_interface.h    
INC += ur_rtde/rtde_utility.h              
INC += ur_rtde/dashboard_enums.h           
INC += ur_rtde/rtde_control_script.h       
INC += ur_rtde/robotiq_gripper.h           
INC += ur_rtde/rtde_control_interface_doc.h
INC += ur_rtde/dashboard_client.h          
INC += ur_rtde/rtde_io_interface.h         
INC += ur_rtde/rtde_control_interface.h    
INC += ur_rtde/rtde_export.h               
INC += ur_rtde/script_client.h             
INC += ur_rtde/robot_state.h               
INC += ur_rtde/rtde.h                      
INC += ur_rtde/rtde_io_interface_doc.h     
INC += urcl/tcp_socket.h
INC += urcl/server.h
INC += urcl/script_sender.h

LIB_INSTALLS    += ../os/rhel8/librtde.a
BIN_INSTALLS    += ../os/rhel8/librtde.so
BIN_INSTALLS    += ../os/rhel8/librtde.so.1.4
BIN_INSTALLS    += ../os/rhel8/librtde.so.1.4.4

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

